pipeline {
    agent any

    stages {
        stage('Portal Web Pipeline') {
            when {
                anyOf {
                    changeset "portal-web/**"
                    triggeredBy 'UserIdCause'
                }
            }

            stages {
                stage('Build') {
                    agent {
                        docker { 
                            image 'node:22-alpine' 
                            reuseNode true
                        }
                    }
                    steps {
                        dir('portal-web') {
                            sh 'npm install && npm run build'
                        }
                    }
                }

                stage('Test') {
                    agent {
                        docker { 
                            image 'node:22-alpine' 
                            reuseNode true
                        }
                    }
                    steps {
                        dir('portal-web') {
                            sh 'npm run test'
                        }
                    }
                }

                stage('Deploy') {
                    agent {
                        docker { 
                            image 'amazon/aws-cli' 
                            args '--entrypoint=""' // Override entrypoint so Jenkins can run sh commands
                            reuseNode true
                        }
                    }
                    steps {
                        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-id', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                            dir('portal-web') {
                                parallel(
                                    'Deploy Login': {
                                        sh "aws s3 sync dist/login s3://${LOGIN_S3_BUCKET} --delete --region ${AWS_REGION} --no-progress"
                                        sh "aws cloudfront create-invalidation --distribution-id ${LOGIN_CF_ID} --paths '/*' --region ${AWS_REGION}"
                                    },
                                    'Deploy Student': {
                                        sh "aws s3 sync dist/student s3://${STUDENT_S3_BUCKET} --delete --region ${AWS_REGION} --no-progress"
                                        sh "aws cloudfront create-invalidation --distribution-id ${STUDENT_CF_ID} --paths '/*' --region ${AWS_REGION}"
                                    },
                                    'Deploy Parent': {
                                        sh "aws s3 sync dist/parent s3://${PARENT_S3_BUCKET} --delete --region ${AWS_REGION} --no-progress"
                                        sh "aws cloudfront create-invalidation --distribution-id ${PARENT_CF_ID} --paths '/*' --region ${AWS_REGION}"
                                    },
                                    'Deploy Faculty': {
                                        sh "aws s3 sync dist/faculty s3://${FACULTY_S3_BUCKET} --delete --region ${AWS_REGION} --no-progress"
                                        sh "aws cloudfront create-invalidation --distribution-id ${FACULTY_CF_ID} --paths '/*' --region ${AWS_REGION}"
                                    }
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}