spring.application.name=student-general-profile-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/student_general_profile
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.error.include-message=always

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# AWS S3 & CloudFront
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:pec-student-profiles}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.cloudfront.domain=${AWS_CLOUDFRONT_DOMAIN:https://cdn.example.com}
